  KoekalenteriApi:
    Type: AWS::Serverless::Api
    Properties:
      MethodSettings:
        - ResourcePath: '/*'
          HttpMethod: '*'
          DataTraceEnabled: false
          MetricsEnabled: false
          LoggingLevel: INFO

        # enable metrics for these paths
        - ResourcePath: '/event'
          HttpMethod: 'GET'
          MetricsEnabled: true

        - ResourcePath: '/event/{id}'
          HttpMethod: 'GET'
          MetricsEnabled: true

        - ResourcePath: '/file/{key}/{name}'
          HttpMethod: 'GET'
          MetricsEnabled: true

        - ResourcePath: '/dog/{regNo}'
          HttpMethod: 'GET'
          MetricsEnabled: true

        - ResourcePath: '/registration/{eventId}/{id}'
          HttpMethod: 'GET'
          MetricsEnabled: true

        - ResourcePath: '/startlist/{eventId}'
          HttpMethod: 'GET'
          MetricsEnabled: true

        - ResourcePath: '/yearly-stats'
          HttpMethod: 'GET'
          MetricsEnabled: true

        - ResourcePath: '/user'
          HttpMethod: 'GET'
          MetricsEnabled: true

        - ResourcePath: '/registration'
          HttpMethod: 'POST'
          MetricsEnabled: true

      AccessLogSetting:
        DestinationArn: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:${ApiAccessLogGroup}'
        Format: '$context.identity.sourceIp $context.authorizer.claims.sub [$context.requestTime] "$context.httpMethod $context.resourcePath $context.protocol" $context.status $context.requestId $context.awsEndpointRequestId $context.xrayTraceId $context.responseLatency $context.integrationLatency "$context.error.message"'
      Name: !Join ['-', [Koekalenteri, !Ref AWS::StackName]]
      StageName: !Ref StageNameParam
      OpenApiVersion: '3.0.1' # prevents the default 'Stage' creation
      TracingEnabled: false
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'OPTIONS,HEAD,GET,PUT,POST,DELETE'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt "KoekalenteriUserPool.Arn"
      BinaryMediaTypes:
        - "multipart/form-data"
        - "application/pdf"
        - "text/html" # default first ACCEPT header for all browsers
      GatewayResponses:
        UNAUTHORIZED:
          StatusCode: 401
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
        ACCESS_DENIED:
          StatusCode: 403
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
        DEFAULT_5XX:
          StatusCode: 500
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
        RESOURCE_NOT_FOUND:
          StatusCode: 404
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"

  ApiGatewayPushToCloudWatchRole:
    Type: "AWS::IAM::Role"
    Properties:
      Description: "Push logs to CloudWatch logs from API Gateway"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"

  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/AccessLog-${KoekalenteriApi}
      RetentionInDays: 365
