  KoekalenteriHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageNameParam
      AccessLogSettings:
        DestinationArn: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:${HttpApiAccessLogGroup}'
        Format: '{"requestTime":"$context.requestTime","requestId":"$context.requestId","httpMethod":"$context.httpMethod","routeKey":"$context.routeKey","status":"$context.status","protocol":"$context.protocol","responseLength":"$context.responseLength","integrationError":"$context.integrationErrorMessage","sourceIp":"$context.identity.sourceIp"}'
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - OPTIONS
          - HEAD
          - GET
          - PUT
          - POST
          - DELETE
        AllowHeaders:
          - Content-Type
          - X-Amz-Date
          - Authorization
          - X-Api-Key
          - X-Amz-Security-Token
      Auth:
        Authorizers:
          JwtAuthorizer:
            JwtConfiguration:
              issuer: !Ref AuthJwtIssuer
              audience:
                - !Ref AuthJwtAudience
            IdentitySource: "$request.header.Authorization"

  ApiGatewayPushToCloudWatchRole:
    Type: "AWS::IAM::Role"
    Properties:
      Description: "Push logs to CloudWatch logs from API Gateway"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"

  HttpApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/AccessLog-${KoekalenteriHttpApi}
      RetentionInDays: 365
