  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
        LayerName: lambda-shared
        Description: Shared resources between lambdas
        ContentUri: layer/
        CompatibleRuntimes:
          - nodejs20.x
        LicenseInfo: 'MIT'
        RetentionPolicy: Retain
