  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: lambda-dependencies
      Description: NPM dependencies shared between lambdas
      ContentUri: dependencies-layer/
      CompatibleRuntimes:
        - nodejs24.x
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain
