AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Koekalenteri"

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 60
    Tracing: Active
    MemorySize: 1024 # From Lambda Power Tuner - https://lambda-power-tuning.show/#gAAAAQACAAQACMAL;Fu+DQkrxg0JplAJBPCnQQBhL0EDm+NlA;m1ZfNJtW3zSbVl81m1bfNZtWXzaaA6Q2
    Tags:
      Application: serverless-web-app
    Environment:
      Variables:
        NODE_PATH: /opt/nodejs/node_modules # needed for layer imports to work without custom build
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
        USE_NGROK: !Ref UseNgrokParam
        USE_CLOUDFLARED: !Ref UseCloudflaredParam
        CUSTOM_DOMAIN: !Ref CustomDomain
        STACK_NAME: !Ref AWS::StackName
        STAGE_NAME: !Ref StageNameParam
        AUDIT_TABLE_NAME: !Ref AuditTable
        DOG_TABLE_NAME: !Ref DogTable
        EMAIL_TEMPLATE_TABLE_NAME: !Ref EmailTemplatesTable
        EVENT_TABLE_NAME: !Ref EventTable
        EVENT_TYPE_TABLE_NAME: !Ref EventTypeTable
        JUDGE_TABLE_NAME: !Ref JudgeTable
        OFFICIAL_TABLE_NAME: !Ref OfficialTable
        ORGANIZER_TABLE_NAME: !Ref OrganizerTable
        REGISTRATION_TABLE_NAME: !Ref EventRegistrationTable
        TRANSACTION_TABLE_NAME: !Ref TransactionTable
        USER_LINK_TABLE_NAME: !Ref UserLinkTable
        USER_TABLE_NAME: !Ref UserTable
        EVENT_STATS_TABLE_NAME: !Ref EventStatsTable
  Api:
    Auth:
      UsagePlan:
        UsagePlanName: DailyUsagePlan
        CreateUsagePlan: PER_API
        Description: This will limit 5000 executions per day and throttle executions on 10% of that.
        Quota:
          Limit: 5000
          Period: DAY
        Throttle:
          BurstLimit: 100
          RateLimit: 50

Parameters:
  StageNameParam:
    Type: String
    Default: prod
  CognitoDomainName:
    Type: String
    Default: koekalenteri
  UseNgrokParam:
    Type: String
    Default: "false"
    Description: Set to "true" when using Ngrok for local development
  UseCloudflaredParam:
    Type: String
    Default: "false"
    Description: Set to "true" when using Cloudflared for local development

  # For Amplify Console frontend hosting
  Repository:
    Type: String
    Description: GitHub Repository URL
  Branch:
    Type: String
    Description: GitHub Branch
    Default: main
  OauthToken:
    Type: String
    Description: GitHub Oauth Token
    NoEcho: true
  CustomDomain:
    Type: String
    Description: Custom domain for Amplify APP
    NoEcho: true

  # For Identity providers
  GoogleClientId:
    Type: String
    Description: Google Client ID
    NoEcho: true

  GoogleClientSecret:
    Type: String
    Description: Google Client Secret
    NoEcho: true

Resources:
