  WebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Join ['-', [Koekalenteri, 'WebSocket', !Ref AWS::StackName]]
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.action

  WebSocketApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref WebSocketApi
      StageName: !Ref StageNameParam
      AutoDeploy: true
