DogTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: !Join ['-', [dog-table, !Ref AWS::StackName]]
    KeySchema:
      - AttributeName: regNo
        KeyType: HASH
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: N
      - AttributeName: regNo
        AttributeType: S
    GlobalSecondaryIndexes:
      - IndexName: gsiIs
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        Projection:
          ProjectionType: ALL
    Tags:
      - Key: Env
        Value: !Ref AWS::StackName
      - Key: Label
        Value: 'koekalenteri'
    BillingMode: PAY_PER_REQUEST
    SSESpecification:
      SSEEnabled: false
