  EmailTemplatesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ['-', [email-templates-table, !Ref AWS::StackName]]
      KeySchema:
          - AttributeName: id
            KeyType: HASH
      AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
      Tags:
        - Key: Env
          Value: !Ref AWS::StackName
        - Key: Label
          Value: "koekalenteri"
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: false
