  EventRegistrationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ['-', [event-registration-table, !Ref AWS::StackName]]
      KeySchema:
          - AttributeName: eventId
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
      AttributeDefinitions:
          - AttributeName: eventId
            AttributeType: S
          - AttributeName: id
            AttributeType: S
      Tags:
        - Key: Env
          Value: !Ref AWS::StackName
        - Key: Label
          Value: "koekalenteri"
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: false
