  WsConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ['-', [ws-connections-table, !Ref AWS::StackName]]
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
      Tags:
        - Key: Env
          Value: !Ref AWS::StackName
        - Key: Label
          Value: "koekalenteri"
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: false
