version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "automerge"
      - "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "automerge"
      - "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      deps:
        patterns:
          - "*"
        exclude-patterns:
          - "camelcase"
          - "@mui/*"

  - package-ecosystem: "npm"
    directory: "/cf/sse-worker"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "automerge"
      - "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      deps:
        patterns:
          - "*"
