version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/koekalenteri-backend"
    schedule:
      interval: "weekly"
    groups:
      deps:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/koekalenteri-frontend"
    schedule:
      interval: "weekly"
    groups:
      deps:
        patterns:
          - "*"
        exclude-patterns:
          - "camelcase"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      deps:
        patterns:
          - "*"
