---
root: true

parser: "@typescript-eslint/parser"
extends:
  - eslint:recommended
  - plugin:react/jsx-runtime
  - plugin:@typescript-eslint/recommended
  - prettier

plugins:
  - react
  - react-hooks
  - unused-imports
  - simple-import-sort
  - mui-path-imports
  - import
  - prettier

env:
  browser: true
  node: true
  es6: true

rules:
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps:
  - warn
  - additionalHooks: '(useRecoilCallback)'
  prettier/prettier: error
  arrow-body-style: 'off'
  prefer-arrow-callback: 'off'
  semi:
  - error
  - never
  quotes:
  - error
  - single
  - avoidEscape: true
    allowTemplateLiterals: true
  comma-spacing:
  - error
  - before: false
    after: true
  mui-path-imports/mui-path-imports: error
  "@typescript-eslint/no-explicit-any": 'off' # TODO
  "@typescript-eslint/no-unused-vars": 'off' # TODO
  "@typescript-eslint/indent": 'off'
  "@typescript-eslint/consistent-type-imports":
  - error
  - prefer: type-imports
  simple-import-sort/imports:
  - error
  - groups:
    - - "^@?\\w.*\\u0000$"
      - "^[^.].*\\u0000$"
      - "^\\..*\\u0000$"
    - - "^react"
      - "^@?\\w"
    - - "^(@|components)(/.*|$)"
    - - "^\\u0000"
    - - "^\\.\\.(?!/?$)"
      - "^\\.\\./?$"
    - - "^\\./(?=.*/)(?!/?$)"
      - "^\\.(?!/?$)"
      - "^\\./?$"
    - - "^.+\\.?(css)$"
  unused-imports/no-unused-imports: error
  import/no-duplicates: error
  import/consistent-type-specifier-style: error
