version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "amplify-koekalenteri"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-koekalenteri"
s3_prefix = "koekalenteri-prod"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "VersionParam=\"v1\" StageNameParam=\"prod\" CognitoDomainName=\"koekalenteri-prod\" Repository=\"https://github.com/koekalenteri/koekalenteri\" Branch=\"main\" OauthToken=\"foobar\""

[dev.deploy.parameters]
stack_name = "amplify-koekalenteri-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-koekalenteri"
s3_prefix = "koekalenteri-dev"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "VersionParam=\"v1\" StageNameParam=\"dev\" CognitoDomainName=\"koekalenteri-dev\" Repository=\"https://github.com/koekalenteri/koekalenteri\" Branch=\"dev\" OauthToken=\"foobar\""
