  PaymentCancelFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/PaymentCancelFunction
      Handler: handler.default
      Layers:
        - !Ref CommonLayer
      Tracing: Active
      Policies:
        - Statement:
            - Sid: SSMGetParameterPolicy
              Effect: Allow
              Action:
              - ssm:GetParameters
              - ssm:GetParameter
              Resource: '*'
        - DynamoDBCrudPolicy:
            TableName: !Ref TransactionTable
        - DynamoDBCrudPolicy:
            TableName: !Ref EventRegistrationTable
        - DynamoDBReadPolicy:
            TableName: !Ref OrganizerTable
        - DynamoDBReadPolicy:
            TableName: !Ref EventTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AuditTable
        - CloudWatchPutMetricPolicy: {}
      Events:
        PutEvent:
          Type: Api
          Properties:
            Path: /payment/cancel
            Method: GET
            RestApiId: !Ref KoekalenteriApi

  PaymentCancelFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref PaymentCancelFunction]]
      RetentionInDays: 30
