  PaymentCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/PaymentCreateFunction
      Handler: handler.default
      Layers:
        - !Ref CommonLayer
      Tracing: Active
      Policies:
        - Statement:
            - Sid: SSMGetParameterPolicy
              Effect: Allow
              Action:
              - ssm:GetParameters
              - ssm:GetParameter
              Resource: '*'
        - DynamoDBCrudPolicy:
            TableName: !Ref TransactionTable
        - DynamoDBCrudPolicy:
            TableName: !Ref EventRegistrationTable
        - DynamoDBReadPolicy:
            TableName: !Ref OrganizerTable
        - DynamoDBReadPolicy:
            TableName: !Ref EventTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AuditTable
        - CloudWatchPutMetricPolicy: {}
      Events:

        PutEventHttpApi:
          Type: HttpApi
          Properties:
            Path: /payment/create
            Method: POST
            ApiId: !Ref KoekalenteriHttpApi

  PaymentCreateFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref PaymentCreateFunction]]
      RetentionInDays: 180
