  GetStartListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/GetStartListFunction
      Handler: handler.default
      Layers:
        - !Ref CommonLayer
      Tracing: PassThrough
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref EventRegistrationTable
        - DynamoDBReadPolicy:
            TableName: !Ref EventTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserLinkTable
        - CloudWatchPutMetricPolicy: {}
      Events:
        GetRegistration:
          Type: Api
          Properties:
            Path: /startlist/{eventId}
            Method: GET
            RestApiId: !Ref KoekalenteriApi
        PreviewStartList:
          Type: Api
          Properties:
            Path: /admin/startlist/{eventId}
            Method: GET
            RestApiId: !Ref KoekalenteriApi
            Auth:
              Authorizer: CognitoAuthorizer

  GetStartListFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref GetStartListFunction]]
      RetentionInDays: 30
