  GetStatsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/GetStatsFunction
      Handler: handler.default
      Layers:
        - !Ref DependenciesLayer
      Tracing: Active
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref EventStatsTable
      Events:
        StatsApi:
          Type: Api
          Properties:
            Path: /stats
            Method: GET
            RestApiId: !Ref KoekalenteriApi

  GetStatsFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref GetStatsFunction]]
      RetentionInDays: 30
