/**
 * Writes e2e/TESTS.md, the list of browser tests, from the tests themselves: Playwright lists them
 * with their titles, tags and annotations without running anything (KOE-1486).
 *
 *   npm run e2e-catalog              rewrite e2e/TESTS.md
 *   npm run e2e-catalog -- --check   fail if e2e/TESTS.md is not what the tests say (lint-e2e, CI)
 */
import { spawnSync } from 'node:child_process'
import fs from 'node:fs'

const CATALOG = 'e2e/TESTS.md'
const JIRA = 'https://koekalenteri.atlassian.net/browse'

const listed = spawnSync('npx', ['playwright', 'test', '--list', '--reporter=json'], {
  encoding: 'utf8',
  maxBuffer: 16 * 1024 * 1024,
})
if (listed.status !== 0) {
  console.error(listed.stderr || listed.stdout)
  process.exit(1)
}
const { suites } = JSON.parse(listed.stdout)

/** Every test with the titles of the describe blocks around it, in file order. */
const collect = (suite, path = []) => [
  ...(suite.specs ?? []).map((spec) => ({ ...spec, path })),
  ...(suite.suites ?? []).flatMap((child) => collect(child, [...path, child.title])),
]

const issueLink = (description) => {
  const [key, ...note] = description.split(' ')
  const link = `[${key}](${JIRA}/${key})`
  return note.length ? `${link} ${note.join(' ')}` : link
}

const escapeCell = (text) => text.replaceAll('|', '\\|')

const lines = [
  '# Browser tests',
  '',
  '<!-- Generated by e2e/catalog.mjs from the tests themselves; do not edit. Run `npm run e2e-catalog`. -->',
  '',
  'What the browser tests claim, one line per test. The issue is the story a test belongs to, or a',
  'bug it works around or expects; **known bug** marks a test that is expected to fail until its',
  'bug is fixed. See [README.md](README.md) for how they run.',
  '',
]
let total = 0
for (const file of suites) {
  const specs = collect(file)
  total += specs.length
  lines.push(`## ${file.file}`, '', '| Test | Tags | Issues |', '| --- | --- | --- |')
  for (const spec of specs) {
    const annotations = spec.tests[0]?.annotations ?? []
    const title = [...spec.path, spec.title].join(' › ')
    const knownBug = annotations.some((annotation) => annotation.type === 'fail') ? ' **known bug**' : ''
    const tags = spec.tags.map((tag) => `\`@${tag}\``).join(' ')
    const issues = annotations
      .filter((annotation) => annotation.type === 'issue')
      .map((annotation) => issueLink(annotation.description))
      .join('<br>')
    lines.push(`| ${escapeCell(title)}${knownBug} | ${tags} | ${escapeCell(issues)} |`)
  }
  lines.push('')
}
lines.push(`${total} tests.`, '')
const catalog = lines.join('\n')

if (process.argv.includes('--check')) {
  const current = fs.existsSync(CATALOG) ? fs.readFileSync(CATALOG, 'utf8') : ''
  if (current !== catalog) {
    console.error(`${CATALOG} does not match the tests. Run: npm run e2e-catalog`)
    process.exit(1)
  }
  console.log(`${CATALOG} matches the ${total} tests.`)
} else {
  fs.writeFileSync(CATALOG, catalog)
  console.log(`Wrote ${CATALOG}: ${total} tests.`)
}
