  DemoEventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/DemoEventsFunction
      Handler: handler.default
      Layers:
        - !Ref CommonLayer
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventTable
        - DynamoDBCrudPolicy:
            TableName: !Ref EventRegistrationTable
        - CloudWatchPutMetricPolicy: {}
      Events:
        DemoEvents:
          Type: Api
          Properties:
            Path: /cron/demo-events
            Method: GET
            RestApiId: !Ref KoekalenteriApi

  DemoEventsFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref DemoEventsFunction]]
      RetentionInDays: 30
