---
root: true

parser: "@typescript-eslint/parser"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended

plugins:
  - "@typescript-eslint"
  - simple-import-sort
  - prettier

env:
  node: true
  es6: true

parserOptions:
  ecmaVersion: 2021
  sourceType: module

rules:
  semi:
    - error
    - never
  prettier/prettier:
    - error
  simple-import-sort/imports:
    - error
    - groups:
      - - "^@?\\w.*\\u0000$"
        - "^[^.].*\\u0000$"
        - "^\\..*\\u0000$"
      - - "^@?\\w"
      - - "^(@|components)(/.*|$)"
      - - "^\\u0000"
      - - "^\\.\\.(?!/?$)"
        - "^\\.\\./?$"
      - - "^\\./(?=.*/)(?!/?$)"
        - "^\\.(?!/?$)"
        - "^\\./?$"
      - - "^.+\\.?(css)$"
  "@typescript-eslint/consistent-type-imports":
      - error
      - prefer: 'type-imports'
