---
root: true

parser: "@typescript-eslint/parser"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended

plugins:
  - "@typescript-eslint"
  - simple-import-sort

env:
  node: true
  es6: true

parserOptions:
  ecmaVersion: 2021
  sourceType: module

rules:
  semi:
    - error
    - never
  comma-dangle:
    - error
    - always-multiline
  comma-spacing:
    - error
    -
      before: false
      after: true
  "@typescript-eslint/indent":
    - error
    - 2
  simple-import-sort/imports:
    - error
    - groups:
      - - react
        - "^@?\\w"
      - - "^(@|components)(/.*|$)"
      - - "^\\u0000"
      - - "^\\.\\.(?!/?$)"
        - "^\\.\\./?$"
      - - "^\\./(?=.*/)(?!/?$)"
        - "^\\.(?!/?$)"
        - "^\\./?$"
      - - "^.+\\.?(css)$"

