import { render, screen } from '@testing-library/react'
import { DndProvider } from 'react-dnd'
import { HTML5Backend } from 'react-dnd-html5-backend'
import DraggableRow from './DraggableRow'

// DraggableRow uses `useGridApiContext()` to verify the row exists in grid state.
// In unit tests we render it in isolation, so we provide a minimal DataGrid api.
jest.mock('@mui/x-data-grid', () => {
  const actual = jest.requireActual('@mui/x-data-grid')
  const React = jest.requireActual('react')

  return {
    ...actual,
    GridRow: React.forwardRef(({ children, style, className, ...rest }: any, ref: any) => (
      // Do not spread unknown props to the DOM to avoid React warnings.
      // biome-ignore lint/a11y/useAriaPropsSupportedByRole: its a test
      <div
        data-testid="grid-row"
        ref={ref}
        style={style}
        className={className}
        // Keep only safe / asserted attributes
        aria-label={rest['aria-label']}
        data-handler-id={rest['data-handler-id']}
      >
        {children}
      </div>
    )),
    useGridApiContext: () => ({
      current: {
        getRow: (id: any) => ({ id }),
      },
    }),
  }
})

jest.mock('./position', () => ({
  determinePosition: jest.fn().mockReturnValue('before'),
}))

describe('DraggableRow', () => {
  const renderWithDnd = (ui: React.ReactElement) => {
    return render(<DndProvider backend={HTML5Backend}>{ui}</DndProvider>)
  }

  // Create base props required by GridRowProps
  const baseProps = {
    cellFocus: false,
    cellTabIndex: -1,
    columnsTotalWidth: 1000,
    editRowsState: {},
    firstColumnIndex: 0,
    firstColumnToRender: 0,
    focusedColumnIndex: undefined,
    gridHasFiller: false,
    groupKey: 'group1',
    id: 'test-id',
    index: 0,
    isFirstVisible: false,
    isLastVisible: false,
    isNotVisible: false,
    lastColumnIndex: 0,
    lastColumnToRender: 10,
    offsetLeft: 0,
    pinnedColumns: { left: [], right: [] },
    position: 'center',
    renderedColumns: [],
    row: { dropGroups: ['group1'] },
    rowHeight: 40,
    rowId: 'test-id',
    rowIndex: 0,
    scrollbarWidth: 0,
    selected: false,
    showBottomBorder: false,
    tabbableCell: null,
    visibleColumns: [],
  }

  it('should render GridRow with correct props', () => {
    renderWithDnd(<DraggableRow {...baseProps} />)

    const gridRow = screen.getByTestId('grid-row')
    expect(gridRow).toBeInTheDocument()
    expect(gridRow).toHaveStyle('opacity: 1') // Not dragging, so opacity should be 1
  })

  it('should apply className when hovered', () => {
    // This is difficult to test directly because it requires simulating
    // the drag and drop behavior, which is challenging in a unit test.
    // We would need to mock the useDrop hook's return value.

    // For now, we'll just verify that the component renders without errors
    renderWithDnd(<DraggableRow {...baseProps} />)

    expect(screen.getByTestId('grid-row')).toBeInTheDocument()
  })

  it('should pass data-handler-id to GridRow', () => {
    renderWithDnd(<DraggableRow {...baseProps} />)

    // The handler ID is generated by react-dnd, so we can't know its exact value
    // We just check that the attribute exists
    const gridRow = screen.getByTestId('grid-row')
    expect(gridRow).toHaveAttribute('data-handler-id')
  })

  it('should pass all props to GridRow', () => {
    const testProps = {
      ...baseProps,
      'aria-label': 'Test Row',
      groupKey: 'group1',
      index: 0,
      row: { dropGroups: ['group1'] },
      rowId: 'test-id',
    }

    renderWithDnd(<DraggableRow {...testProps} />)

    const gridRow = screen.getByTestId('grid-row')
    expect(gridRow).toHaveAttribute('aria-label', 'Test Row')
  })
})
