import type { ConfirmedEvent } from '../../types'

export const emptyEvent: ConfirmedEvent = {
  accountNumber: 'test',
  classes: [{ class: 'ALO' }],
  cost: 123,
  costMember: 123,
  createdAt: new Date('1989-01-01'),
  createdBy: 'test',
  description: 'test',
  endDate: new Date('1990-01-01'),
  entries: 0,
  entryEndDate: new Date('1990-01-01'),
  entryStartDate: new Date('1990-01-01'),
  eventType: 'test',
  id: 'test',
  judges: [123],
  kcId: 123456,
  location: 'test',
  modifiedAt: new Date('1989-01-02'),
  modifiedBy: 'test',
  name: 'test',
  official: {
    id: 1,
    name: 'Teemu Toimitsija',
    email: 'joo@ei.com',
    phone: '040-official',
    location: 'Suomi',
    district: 'Helsinki',
    eventTypes: ['test'],
  },
  priority: ['member'],
  secretary: {
    id: 2,
    name: 'Siiri Sihteeri',
    email: 'ei@joo.com',
    phone: '040-secretary',
    location: 'Ruotsi',
  },
  organizer: {
    id: '1',
    name: 'Suomen Noutajakoirajärjestö ry',
  },
  paymentDetails: 'test',
  places: 10,
  referenceNumber: 'test',
  startDate: new Date('1990-01-01'),
  state: 'confirmed' as const,
}
