  EventAttachmentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Join ['-', [!Ref AWS::StackName, 'event-attachments']]
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: # Headers that are specified in the Access-Control-Request-Headers header. These headers are allowed in a preflight OPTIONS request. In response to any preflight OPTIONS request, Amazon S3 returns any requested headers that are allowed.
              - '*'
            AllowedMethods: # An HTTP method that you allow the origin to run. Allowed values: GET | PUT | HEAD | POST | DELETE
              - GET
            AllowedOrigins: # One or more origins you want customers to be able to access the bucket from.
              - '*'
            ExposedHeaders: # One or more headers in the response that you want customers to be able to access from their applications (for example, from a JavaScript XMLHttpRequest object).
              - Date
            Id: EventAttachmentCORSRule # A unique identifier for this rule. The value must be no more than 255 characters.
            MaxAge: 3600 # The time in seconds that your browser is to cache the preflight response for the specified resource.
      LoggingConfiguration:
        DestinationBucketName: !Ref S3BucketLogs
        LogFilePrefix: event-attachment-logs
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
