  CopyEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/CopyEventFunction
      Handler: handler.default
      Layers:
        - !Ref CommonLayer
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventTable
        - DynamoDBCrudPolicy:
            TableName: !Ref EventRegistrationTable
        - DynamoDBReadPolicy:
            TableName: !Ref UserTable
        - DynamoDBReadPolicy:
            TableName: !Ref UserLinkTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AuditTable
        - CloudWatchPutMetricPolicy: {}
      Events:
        CopyEvent:
          Type: Api
          Properties:
            Path: /admin/event/copy
            Method: POST
            RestApiId: !Ref KoekalenteriApi
            Auth:
              Authorizer: JwtAuthorizer

  CopyEventFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref CopyEventFunction]]
      RetentionInDays: 30
