  GetAdminStatsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/GetAdminStatsFunction
      Handler: handler.default
      Layers:
        - !Ref DependenciesLayer
      Tracing: Active
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref EventStatsTable
        - DynamoDBReadPolicy:
            TableName: !Ref UserTable
        - DynamoDBReadPolicy:
            TableName: !Ref UserLinkTable
      Events:
        GetAdminStatsApi:
          Type: Api
          Properties:
            Path: /admin/stats
            Method: GET
            RestApiId: !Ref KoekalenteriApi
            Auth:
              Authorizer: CognitoAuthorizer

  GetAdminStatsFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref GetAdminStatsFunction]]
      RetentionInDays: 30
