  GetEventTypesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/GetEventTypesFunction
      Handler: handler.default
      Policies:
        - Statement:
            - Sid: SSMGetParameterPolicy
              Effect: Allow
              Action:
              - ssm:GetParameters
              - ssm:GetParameter
              Resource: '*'
        - CloudWatchPutMetricPolicy: {}
        - DynamoDBCrudPolicy:
            TableName: !Ref EventTypeTable
        - DynamoDBReadPolicy:
            TableName: !Ref UserTable
        - DynamoDBReadPolicy:
            TableName: !Ref UserLinkTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AuditTable
        - DynamoDBCrudPolicy:
            TableName: !Ref DataVersionTable
        - !Ref WebSocketPolicy
      Events:
        GetEventTypes:
          Type: Api
          Properties:
            Path: /admin/eventType
            Method: GET
            RestApiId: !Ref KoekalenteriApi
            Auth:
              Authorizer: CognitoAuthorizer
