  GetUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/GetUsersFunction
      Handler: handler.default
      Layers:
        - !Ref CommonLayer
      Tracing: Active
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UserTable
        - DynamoDBReadPolicy:
            TableName: !Ref UserLinkTable
        - CloudWatchPutMetricPolicy: {}
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /admin/user
            Method: GET
            RestApiId: !Ref KoekalenteriApi
            Auth:
              Authorizer: CognitoAuthorizer # NB: CognitoAuthorizer does not work locally https://github.com/aws/aws-sam-cli/issues/137

  GetUsersFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref GetUsersFunction]]
      RetentionInDays: 30
