  GetEventTypesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/GetEventTypesFunction
      Handler: handler.default
      Layers:
        - !Ref CommonLayer
      Tracing: Active
      Policies:
        - Statement:
            - Sid: SSMGetParameterPolicy
              Effect: Allow
              Action:
              - ssm:GetParameters
              - ssm:GetParameter
              Resource: '*'
        - CloudWatchPutMetricPolicy: {}
        - DynamoDBCrudPolicy:
            TableName: !Ref EventTypeTable
        - DynamoDBReadPolicy:
            TableName: !Ref UserTable
        - DynamoDBReadPolicy:
            TableName: !Ref UserLinkTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AuditTable
      Events:
        GetEventTypes:
          Type: Api
          Properties:
            Path: /admin/eventType
            Method: GET
            RestApiId: !Ref KoekalenteriApi
            Auth:
              Authorizer: JwtAuthorizer

  GetEventTypesFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref GetEventTypesFunction]]
      RetentionInDays: 30
