  PutEmailTemplateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/PutEmailTemplateFunction
      Handler: handler.default
      Layers:
        - !Ref CommonLayer
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EmailTemplatesTable
        - DynamoDBReadPolicy:
            TableName: !Ref UserTable
        - DynamoDBReadPolicy:
            TableName: !Ref UserLinkTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AuditTable
        - CloudWatchPutMetricPolicy: {}
        - Statement:
            - Sid: SESTemplatesPolicy
              Effect: Allow
              Action:
              - ses:getTemplate
              - ses:createTemplate
              - ses:updateTemplate
              Resource: '*'
      Events:
        PutEmailTemplate:
          Type: Api
          Properties:
            Path: /admin/email-templates
            Method: POST
            RestApiId: !Ref KoekalenteriApi
            Auth:
              Authorizer: CognitoAuthorizer

  PutEmailTemplateFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref PutEmailTemplateFunction]]
      RetentionInDays: 30
