  PutAdminRegistrationNotesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/PutAdminRegistrationNotesFunction
      Handler: handler.default
      Layers:
        - !Ref CommonLayer
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventRegistrationTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AuditTable
        - DynamoDBReadPolicy:
            TableName: !Ref UserTable
        - DynamoDBReadPolicy:
            TableName: !Ref UserLinkTable
        - CloudWatchPutMetricPolicy: {}
        - Statement:
            - Sid: SESSendEmailPolicy
              Effect: Allow
              Action:
              - ses:sendTemplatedEmail
              Resource: '*'
      Events:
        PutAdminRegistrationNotes:
          Type: Api
          Properties:
            Path: /admin/registration/note
            Method: POST
            RestApiId: !Ref KoekalenteriApi
            Auth:
              Authorizer: CognitoAuthorizer

  PutAdminRegistrationNotesFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref PutAdminRegistrationNotesFunction]]
      RetentionInDays: 30
