  PutEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/PutEventFunction
      Handler: handler.default
      Layers:
        - !Ref CommonLayer
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventTable
        - DynamoDBReadPolicy:
            TableName: !Ref UserTable
        - DynamoDBReadPolicy:
            TableName: !Ref UserLinkTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AuditTable
        - Statement:
            - Sid: SSMGetParameterPolicy
              Effect: Allow
              Action:
              - ssm:GetParameters
              - ssm:GetParameter
              Resource: '*'
        - CloudWatchPutMetricPolicy: {}
        - !Ref WebSocketPolicy
      Events:
        PutEvent:
          Type: Api
          Properties:
            Path: /admin/event
            Method: POST
            RestApiId: !Ref KoekalenteriApi
            Auth:
              Authorizer: CognitoAuthorizer

  PutEventFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref PutEventFunction]]
      RetentionInDays: 30
