  PutAdminRegistrationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/PutAdminRegistrationFunction
      Handler: handler.default
      Layers:
        - !Ref CommonLayer
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventRegistrationTable
        - DynamoDBCrudPolicy:
            TableName: !Ref EventTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AuditTable
        - DynamoDBCrudPolicy:
            TableName: !Ref EventStatsTable
        - DynamoDBReadPolicy:
            TableName: !Ref UserTable
        - DynamoDBReadPolicy:
            TableName: !Ref UserLinkTable
        - CloudWatchPutMetricPolicy: {}
        - Statement:
            - Sid: SESSendEmailPolicy
              Effect: Allow
              Action:
              - ses:sendTemplatedEmail
              Resource: '*'
        - Statement:
            - Sid: SSMGetParameterPolicy
              Effect: Allow
              Action:
              - ssm:GetParameters
              - ssm:GetParameter
              Resource: '*'
      Events:
        PutAdminRegistration:
          Type: Api
          Properties:
            Path: /admin/registration
            Method: POST
            RestApiId: !Ref KoekalenteriApi
            Auth:
              Authorizer: CognitoAuthorizer

  PutAdminRegistrationFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref PutAdminRegistrationFunction]]
      RetentionInDays: 30
