  RunMigrationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/RunMigrationFunction
      Handler: handler.default
      Layers:
        - !Ref CommonLayer
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventTable
        - DynamoDBCrudPolicy:
            TableName: !Ref EventRegistrationTable
        - DynamoDBReadPolicy:
            TableName: !Ref JudgeTable
        - DynamoDBReadPolicy:
            TableName: !Ref UserTable
        - DynamoDBReadPolicy:
            TableName: !Ref UserLinkTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AuditTable
        - CloudWatchPutMetricPolicy: {}
      Events:
        RunMigration:
          Type: Api
          Properties:
            Path: /admin/migrate
            Method: POST
            RestApiId: !Ref KoekalenteriApi
            Auth:
              Authorizer: CognitoAuthorizer

  RunMigrationFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref RunMigrationFunction]]
      RetentionInDays: 30
