name: Dependabot auto-merge

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve & enable auto-merge
        run: |
          if gh pr checks "$PR_URL" --required --watch --fail-fast; then
            gh pr review --approve "$PR_URL"
            gh pr merge --squash "$PR_URL"
          else
            echo "Status checks failed, skipping."
          fi
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
